# Generated by Django 6.0.7 on 2026-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options_remove_question_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('VOICE', 'Voice Question')], default='MCQ', max_length=10),
        ),
    ]
