# Generated by Django 6.0.7 on 2026-08-22 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0006_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CAMERA_STARTED', 'Camera Started'), ('CAMERA_STOPPED', 'Camera Stopped'), ('MIC_STARTED', 'Microphone Started'), ('MIC_STOPPED', 'Microphone Stopped'), ('TAB_SWITCH', 'Tab Switch'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACE', 'Multiple Faces Detected')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='INFO', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
