# Generated by Django 6.0.7 on 2026-08-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='employee_id',
        ),
    ]
