# Generated by Django 6.0.7 on 2026-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_questions', '0001_initial'),
        ('exams', '0001_initial'),
        ('questions', '0004_question_question_image_alter_question_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='unique_exam_question'),
        ),
    ]
